### ISSUE TITLE
Segmentation fault with version 4.3.0 / Qt5

### ISSUE THREAD

**Issue by akien-mga** [panzi/qjoypad#11]
I just packaged version 4.3.0 built with Qt5 for Mageia Cauldron, and I get a segfault on start:
```
(gdb) bt
#0  0x00000000004141c4 in Axis::read(QTextStream&) (this=0x18, stream=...) at /usr/src/debug/qjoypad-4.3.0/src/axis.cpp:105
#1  0x0000000000419e0a in JoyPad::readConfig(QTextStream&) (this=0x746e90, stream=...) at /usr/src/debug/qjoypad-4.3.0/src/joypad.cpp:178
#2  0x00000000004229ad in LayoutManager::load(QString const&) (this=this@entry=0x7fffffffd860, name=...) at /usr/src/debug/qjoypad-4.3.0/src/layout.cpp:232
#3  0x00000000004264d3 in LayoutManager::load() (this=this@entry=0x7fffffffd860) at /usr/src/debug/qjoypad-4.3.0/src/layout.cpp:276
#4  0x00000000004124d8 in main(int, char**) (argc=1, argv=<optimized out>) at /usr/src/debug/qjoypad-4.3.0/src/main.cpp:247
```

I don't have any joypad connected when doing this test.

**Comment by akien-mga** [comment]
I'm using Qt 5.6.0.

**Comment by panzi** [comment]
While I don't have the crash here, I think I know how I caused it. Is it fixed now for you?

**Comment by akien-mga** [comment]
Thanks, 2ec41e6c fixes the crash.
