### ISSUE TITLE
qjoypad tray icon closes when I press a button on the controller

### ISSUE THREAD

**Issue by luisgflores** [panzi/qjoypad#57]
Hello! Thank you for this great project. 
I installed it on Raspbian using the default APT sources. My third-party PS3 controller gets recognized and I can assign a layout, but then when I try to actually use the controller by pressing a button, the tray icon closes.
Where can I find more useful information?

**Comment by robbi-blechdose** [comment]
Could you try running the program from the command line and posting the log here?

**Comment by cbnathanael** [comment]
The same thing happens to me, with an 8Bitdo SN30 Pro connected with bluetooth. From the terminal, it just crashes with a `Segmentation Fault`. Editing the profile, however, works just fine, and it sees the inputs without a problem. Only after loading a profile and pushing a button/stick does it crash.

I'm attempting to use this on a Raspberry Pi 4, Debian 12 (Bookworm), no special configs or anything.

**Comment by robbi-blechdose** [comment]
Could you run the program via `gdb` to figure out the source of the segfault?
I can't reproduce the issue myself I'm afraid

**Comment by cbnathanael** [comment]
Looks like it's a Wayland issue. I didn't realize the Pi4 defaulted to that.

I switched back to X11 and qjoypad seems to be working normally. 

I'm also running qjoypad after compiling it rather than whatever version is in the apt repos.

```Reading symbols from qjoypad...
(No debugging symbols found in qjoypad)
(gdb) run
Starting program: /usr/bin/qjoypad 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ff2958100 (LWP 9305)]
[New Thread 0x7fea148100 (LWP 9306)]
[New Thread 0x7ff10b9100 (LWP 9319)]
[Thread 0x7ff10b9100 (LWP 9319) exited]
[New Thread 0x7ff10b9100 (LWP 9320)]
[New Thread 0x7ff08a9100 (LWP 9321)]
[Thread 0x7ff10b9100 (LWP 9320) exited]
[New Thread 0x7ff10b9100 (LWP 9322)]
[New Thread 0x7febf05100 (LWP 9323)]
[Thread 0x7ff08a9100 (LWP 9321) exited]
[Thread 0x7ff10b9100 (LWP 9322) exited]
[New Thread 0x7ff10b9100 (LWP 9324)]
[New Thread 0x7ff08a9100 (LWP 9325)]
[Thread 0x7ff10b9100 (LWP 9324) exited]
[Thread 0x7febf05100 (LWP 9323) exited]
[Thread 0x7ff08a9100 (LWP 9325) exited]
[New Thread 0x7ff08a9100 (LWP 9326)]
[New Thread 0x7febf05100 (LWP 9328)]
[New Thread 0x7ff10b9100 (LWP 9329)]
[Thread 0x7febf05100 (LWP 9328) exited]
[New Thread 0x7febf05100 (LWP 9330)]
[New Thread 0x7feb545100 (LWP 9331)]
[Thread 0x7febf05100 (LWP 9330) exited]
[Thread 0x7ff10b9100 (LWP 9329) exited]
[New Thread 0x7ff10b9100 (LWP 9332)]
[New Thread 0x7febf05100 (LWP 9333)]
[Thread 0x7feb545100 (LWP 9331) exited]
[Thread 0x7ff10b9100 (LWP 9332) exited]
[Thread 0x7febf05100 (LWP 9333) exited]

(qjoypad:9303): GLib-GObject-CRITICAL **: 06:56:25.762: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[New Thread 0x7febf05100 (LWP 9334)]
[New Thread 0x7ff10b9100 (LWP 9335)]
[Thread 0x7febf05100 (LWP 9334) exited]
[New Thread 0x7febf05100 (LWP 9336)]
[New Thread 0x7feb545100 (LWP 9337)]
[Thread 0x7febf05100 (LWP 9336) exited]
[Thread 0x7ff10b9100 (LWP 9335) exited]
[New Thread 0x7ff10b9100 (LWP 9338)]
[New Thread 0x7febf05100 (LWP 9339)]
[Thread 0x7feb545100 (LWP 9337) exited]
[Thread 0x7ff10b9100 (LWP 9338) exited]
[Thread 0x7febf05100 (LWP 9339) exited]
[New Thread 0x7febf05100 (LWP 9342)]
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
libpng warning: iCCP: known incorrect sRGB profile

Thread 1 "qjoypad" received signal SIGSEGV, Segmentation fault.
0x0000007ff774a254 in XQueryExtension ()
   from /lib/aarch64-linux-gnu/libX11.so.6```

**Comment by hol430** [comment]
I think I'm seeing the same issue, when using a wayland compositor (hyprland). Here's a stack trace:

```
#0  0x00007ffff7701f45 in _XGetRequest (dpy=0x5555555b72a0, type=98 'b', len=8) at /usr/src/debug/libx11/libX11-1.8.12/src/XlibInt.c:1796
#1  0x00007ffff76f6549 in XQueryExtension (dpy=dpy@entry=0x5555555b72a0, name=name@entry=0x7ffff7f58019 "XInputExtension", 
    major_opcode=major_opcode@entry=0x7fffffffda8c, first_event=first_event@entry=0x7fffffffda90, 
    first_error=first_error@entry=0x7fffffffda94) at /usr/src/debug/libx11/libX11-1.8.12/src/QuExt.c:49
#2  0x00007ffff7f55bdb in get_xinput_base (dpy=0x5555555b72a0) at /usr/src/debug/libxtst/libXtst-1.2.5/src/XTest.c:79
#3  find_display (dpy=0x5555555b72a0) at /usr/src/debug/libxtst/libXtst-1.2.5/src/XTest.c:83
#4  find_display (dpy=dpy@entry=0x5555555b72a0) at /usr/src/debug/libxtst/libXtst-1.2.5/src/XTest.c:83
#5  0x00007ffff7f57096 in XTestFakeKeyEvent (dpy=0x5555555b72a0, keycode=105, is_press=1, delay=0)
    at /usr/src/debug/libxtst/libXtst-1.2.5/src/XTest.c:165
#6  0x000055555556c306 in ?? ()
#7  0x000055555556ad33 in ?? ()
#8  0x000055555556d80c in ?? ()
#9  0x00007ffff6d07705 in doActivate<false> (sender=0x5555557f7ac0, signal_index=5, argv=0x7fffffffdc70) at kernel/qobject.cpp:3940
#10 0x00007ffff6d095a6 in QSocketNotifier::activated (this=this@entry=0x5555557f7ac0, _t1=<optimized out>, _t2=...)
    at .moc/moc_qsocketnotifier.cpp:185
#11 0x00007ffff6d0968a in QSocketNotifier::event (this=0x5555557f7ac0, e=<optimized out>) at kernel/qsocketnotifier.h:115
#12 0x00007ffff7958626 in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x5555557f7ac0, e=0x7fffffffdda0)
    at kernel/qapplication.cpp:3640
#13 0x00007ffff6cd0448 in QCoreApplication::notifyInternal2 (receiver=0x5555557f7ac0, event=0x7fffffffdda0)
    at kernel/qcoreapplication.cpp:1064
#14 0x00007ffff6d278af in socketNotifierSourceDispatch (source=0x5555555b0180) at kernel/qeventdispatcher_glib.cpp:107
#15 0x00007ffff5b06f8d in g_main_dispatch (context=0x7fffec000f20) at ../glib/glib/gmain.c:3565
#16 0x00007ffff5b08657 in g_main_context_dispatch_unlocked (context=0x7fffec000f20) at ../glib/glib/gmain.c:4425
#17 g_main_context_iterate_unlocked (context=context@entry=0x7fffec000f20, block=block@entry=1, dispatch=dispatch@entry=1, 
    self=<optimized out>) at ../glib/glib/gmain.c:4490
#18 0x00007ffff5b08865 in g_main_context_iteration (context=0x7fffec000f20, may_block=1) at ../glib/glib/gmain.c:4556
#19 0x00007ffff6d21dc9 in QEventDispatcherGlib::processEvents (this=0x55555565fa60, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#20 0x00007ffff6cc893b in QEventLoop::exec (this=0x7fffffffe030, flags=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:69
#21 0x00007ffff6cd4c5b in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1375
#22 0x0000555555566959 in ?? ()
#23 0x00007ffff6227635 in __libc_start_call_main (main=main@entry=0x555555565ff0, argc=argc@entry=2, argv=argv@entry=0x7fffffffe468)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#24 0x00007ffff62276e9 in __libc_start_main_impl (main=0x555555565ff0, argc=2, argv=0x7fffffffe468, init=<optimized out>, 
--Type <RET> for more, q to quit, c to continue without paging--
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe458) at ../csu/libc-start.c:360
#25 0x0000555555566ec5 in ?? ()
```
